### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by ms-np** [ms-np/wireframe_group-work#8]
### Add a nice pleasant footer to the web page

* HTML
A pleasant footer

* CSS
Layout styling for the footer

**Comment by snicoll** [comment]
PR #11 does not really implement this issue, does it? This would rather be ab897c6a5a52

**Comment by aleks2407** [comment]
@snicoll , I don't completely understand what happened here))))Could you explain please?
I see the branch `footer` but i don't see the PR for it. A bit confused..

**Comment by snicoll** [comment]
We're both confused :) If you look at the [git history](https://github.com/ms-np/wireframe_group-work/commits/master) of this project you can see that this very issue "Add footer" has been implemented by https://github.com/ms-np/wireframe_group-work/commit/ab897c6a5a52da86ae6443809489b003d02bafed. As far as I can see it has been pushed directly to master without a PR. 

My best guess is that you've tried to have a PR for it anyway but it was too late. https://github.com/ms-np/wireframe_group-work/pull/11/commits/d5db588073812f539d92096c503370dee8aafc2e has a actually a `closes #8` instruction in its commit message so it instructed GitHub to associate this issue with that commit.

**Comment by ms-np** [comment]
@snicoll seems like your guess has some truth in it - it was my piece of website and I developed it on a separate branch but something went wrong after I pushed it as https://github.com/ms-np/wireframe_group-work/commit/ab897c6a5a52da86ae6443809489b003d02bafed got merged automatically - ( I don't think I would be able to reproduce my exact steps now but there're high chances that I merged it to master locally and then pushed - correct me if I'm wrong). 
The automatic merge leaves us with:
* the part of web-site without the review of my partner Alex
* unclosed issue #8 (with an option to close it manually but it will still be out of process)
* absence of the branch that the piece was developed on.

The new commit and related to it PR (https://github.com/ms-np/wireframe_group-work/pull/11/commits/d5db588073812f539d92096c503370dee8aafc2e)  solved all of these 3 issues above (Alex had a chance to review it, new branch was merged, issue closed)  + introduced minor changes to the footer layout.

Is there something wrong about this incident and what is the general flow in such cases should be? (minding the fact that I still don't recall completely my exact actions and not 100% sure how the auto-merge happened).

**Comment by snicoll** [comment]
Yeah if you merged the branch of a PR locally, it's just another way of the "merge PR" button on GitHub really.

The absence of the branch is not a problem.

> The new commit and related to it PR (d5db588) solved all of these 3 issues above

Not really. That PR has a single commit (the minor change to the footer layout). Look at the files change tab in the PR.

>  Is there something wrong about this incident and what is the general flow in such cases should be?

Keep in mind this an exercise so it's not as realistic as what you'd do in an actual project. The key thing to remember here is that you pushed a change without a review. This should not have happened and can be put in the "oops" category. This will happen again and once you've pushed on `master`, there's nothing you can do about it.

If that kind of situation happens again in the future, letting your team knows that a change was pushed without a review is in order. They can review the changes on `master` (i.e. inspect the code). If an issue is found, an issue can be created to describe the problem and you or someone else on the team can work on a fix.
